name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        go-minor: [21, 22, 23, 24, 25, 26, 27]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.${{ matrix.go-minor }}.x

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v ./...

      - name: Test-386
        if: ${{ matrix.os != 'macos-latest' }}
        run: go test -v ./...
        env:
          GOARCH: "386"

      - name: Test-wasm
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          wasm_exec="$(go env GOROOT)/lib/wasm/go_js_wasm_exec"
          if [[ ! -x "$wasm_exec" ]]; then
            wasm_exec="$(go env GOROOT)/misc/wasm/go_js_wasm_exec"
          fi
          GOOS=js GOARCH=wasm go test -exec="$wasm_exec" -v ./...
